MEMORY {
    RAM   (rwx) : ORIGIN = 0x40000000, LENGTH = 128M
    AHEAP (rw)  : ORIGIN = 0x48000000, LENGTH = 384M
}

REGION_ALIAS("REGION_TEXT", RAM)
REGION_ALIAS("REGION_RODATA", RAM)
REGION_ALIAS("REGION_DATA", RAM)
REGION_ALIAS("REGION_BSS", RAM)
REGION_ALIAS("REGION_STACK", RAM)
REGION_ALIAS("REGION_HEAP", AHEAP)

_heap_size = LENGTH(AHEAP);
